version: 4.34.7
build_image: registry.pyn.ru/openjdk11-building:2021.07.06
type: library
build_method: mvn_build
deploy_method: mvn_deploy
update_method: mvn_update
wiki_links:
- https://wiki.hh.ru/x/qo0eEQ
- https://github.com/hhru/nuts-and-bolts/releases
changelog: true
